name: Deploy to GitHub Pages
# Run workflow on every push to the master branch
on: [push]
permissions:
  contents: write
jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code form the master branch
      - uses: actions/checkout@v4
      # sets up .NET Core SDK 3.1
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.1.0
      # publishes Blazor project to the release-folder
      - name: Publish .NET Core Project
        run: dotnet publish BPUpgradeTrackerWasm.csproj -c Release -o release --nologo

      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      - name: Change base-tag in index.html
        run: sed -i 's/<base href="\/" \/>/<base href="\/johnn333.github.io/BP-UpgradeTimes\/" \/>/g' release/wwwroot/index.html
        
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: release/wwwroot

